apiVersion: v2
name: boundary
version: 1.1.5
description: A Helm chart for Hashicorp Boundary deployment
type: application
keywords:
  - Hashicorp
  - Boundary
home: https://boundaryproject.io
sources:
  - https://github.com/hashicorp/boundary
maintainers:
  - name: Ankit
    url: https://charts.livspace.com
appVersion: "0.18.1"
