apiVersion: v1
description: A Helm chart for Kubernetes
name: hydra
version: 1.20.2
maintainers:
  - email: ankit.a@livspace.com
    name: ankit-ls
  - email: praveen@livspace.com
    name: praveen-livspace
