apiVersion: v2
name: caddy
description: |
  The Caddy web server is an extensible, cross-platform, open-source web server written in Go.
type: application
version: 1.3.0
appVersion: "2.9.1"
maintainers:
  - name: Praveen
    email: praveen@livspace.com
    url: www.livspace.com
  - name: Ankit
    email: ankit.a@livspace.com
    url: www.livspace.com
