{{- if $.Values.networkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ template "application.name" . }}-egress
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "application.name" . }}
spec:
  endpointSelector:
    matchLabels:
      app: {{ template "application.name" . }}
  egress:
  {{- if .Values.networkPolicy.egress }}
  {{- range $app := .Values.networkPolicy.egress.toApps }}
  {{- if or $app.httpPorts $app.tcpPorts $app.udpPorts }}
  - toEndpoints:
      - matchLabels:
          "k8s:app": {{ $app.name }}
          {{- if $app.namespace }}
          "k8s:io.kubernetes.pod.namespace": {{ $app.namespace }}
          {{- end }}
    toPorts:
      {{- range $port := $app.httpPorts }}
      - ports: 
        - port: "{{ $port }}"
          protocol: TCP
        rules:
          http: [{}]
      {{- end }}
      {{- range $port := $app.tcpPorts }}
      - ports: 
        - port: "{{ $port }}"
          protocol: TCP
      {{- end }}
      {{- range $port := $app.udpPorts }}
      - ports: 
        - port: "{{ $port }}"
          protocol: UDP
      {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  - toEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: kube-system
          k8s:k8s-app: kube-dns
    toPorts:
      - ports:
        - port: "53"
          protocol: ANY
        rules:
          dns:
          - matchPattern: '*'
{{- end }}