{{- if $.Values.cluster.scService.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.service.name }}-egress
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "fullname" . }}
  policyTypes:
  - Egress
  egress:
  {{- if .Values.cluster.scService.networkPolicy.egress }}
  {{- range $app := .Values.cluster.scService.networkPolicy.egress.toApps }}
  {{- if or $app.httpPorts $app.tcpPorts $app.udpPorts }}
  {{- $labelKey := default "app" $app.labelKey }}
  - to:
    - podSelector:
        matchLabels:
          {{ $labelKey }}: {{ $app.name }}
      {{- if $app.namespace }}
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $app.namespace }}
      {{- end }}
    ports:
    {{- range $port := $app.httpPorts }}
    - port: {{ $port }}
      protocol: TCP
    {{- end }}
    {{- range $port := $app.tcpPorts }}
    - port: {{ $port }}
      protocol: TCP
    {{- end }}
    {{- range $port := $app.udpPorts }}
    - port: {{ $port }}
      protocol: UDP
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
{{- end }}


---

{{- if $.Values.cluster.broker.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.cluster.broker.svc }}-egress
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .Values.cluster.broker.svc }}
spec:
  podSelector:
    matchLabels:
      component: {{ .Values.cluster.broker.svc }}
  policyTypes:
  - Egress
  egress:
  {{- if .Values.cluster.broker.networkPolicy.egress }}
  {{- range $app := .Values.cluster.broker.networkPolicy.egress.toApps }}
  {{- if or $app.httpPorts $app.tcpPorts $app.udpPorts }}
  {{- $labelKey := default "app" $app.labelKey }}
  - to:
    - podSelector:
        matchLabels:
          {{ $labelKey }}: {{ $app.name }}
      {{- if $app.namespace }}
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $app.namespace }}
      {{- end }}
    ports:
    {{- range $port := $app.httpPorts }}
    - port: {{ $port }}
      protocol: TCP
    {{- end }}
    {{- range $port := $app.tcpPorts }}
    - port: {{ $port }}
      protocol: TCP
    {{- end }}
    {{- range $port := $app.udpPorts }}
    - port: {{ $port }}
      protocol: UDP
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
{{- end }}


---

{{- if $.Values.cluster.state.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.cluster.state.svc }}-egress
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .Values.cluster.state.svc }}
spec:
  podSelector:
    matchLabels:
      component: {{ .Values.cluster.state.svc }}
  policyTypes:
  - Egress
  egress:
  {{- if .Values.cluster.state.networkPolicy.egress }}
  {{- range $app := .Values.cluster.state.networkPolicy.egress.toApps }}
  {{- if or $app.httpPorts $app.tcpPorts $app.udpPorts }}
  {{- $labelKey := default "app" $app.labelKey }}
  - to:
    - podSelector:
        matchLabels:
          {{ $labelKey }}: {{ $app.name }}
      {{- if $app.namespace }}
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $app.namespace }}
      {{- end }}
    ports:
    {{- range $port := $app.httpPorts }}
    - port: {{ $port }}
      protocol: TCP
    {{- end }}
    {{- range $port := $app.tcpPorts }}
    - port: {{ $port }}
      protocol: TCP
    {{- end }}
    {{- range $port := $app.udpPorts }}
    - port: {{ $port }}
      protocol: UDP
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
{{- end }}
