apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: app-compat
version: 1.0.61
maintainers:
  - name: Praveen
    email: praveen@livspace.com
    url: www.livspace.com
  - name: Ankit
    email: ankit.a@livspace.com
    url: www.livspace.com
