externalSecretsv2:
  enabled: true
  refreshInterval: "1h"
  secrets:
    - name: "default-infra-database-creds"
      format: "keyvalue"
    - name: "default-core-api-keys"
      format: "string"
      secretKey: "api_key"
      version: "1"
    - name: "staging-finance-payment-gateway"
      format: "keyvalue"
      refreshInterval: "30m"

global:
  environment: "staging"