{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template ".servicename" . }}
  labels:
{{- include "application.labels" . | nindent 4 }}
{{- if .Values.appLabels }}
{{ toYaml .Values.appLabels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end}}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
{{- if (and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges )}}
  loadBalancerSourceRanges:
 {{- range .Values.service.loadBalancerSourceRanges }}
  - {{ . }}
 {{- end }}
{{- end }}
  ports:
    {{- range .Values.ContainerPort }}
      {{- if .servicePort }}
    - port: {{ .servicePort }}
      {{- else }}
    - port: {{ .port }}
       {{- end }}
      {{- if .targetPort }}
      targetPort: {{ .targetPort }}
      {{- else }}
      targetPort: {{ .name }}
      {{- end }}
      protocol: TCP
      {{- if (and (eq $.Values.service.type "NodePort") .nodePort ) }}
      nodePort: {{ .nodePort }}
      {{- end }}
      name: {{ .name }}
    {{- end }}
      {{- if $.Values.appMetrics }}
    - port: 9901
      name: envoy-admin
      {{- end }}
  selector:
    {{ include "application.selectorLabels" . | indent 4 }}
{{- end }}
